### ISSUE TITLE
missing download link in https://learngeb-ebook.readbook.tw/install/groovy.html

### ISSUE THREAD

**Issue by ysyang21** [readbook/learngeb#10]
codehaus.org 已經倒站了, groovy for windows installer 的 repo:

https://bintray.com/groovy/Distributions/Windows-Installer

最近一個版本的安裝程式可在以下地方取得:

https://bintray.com/groovy/Distributions/download_file?file_path=groovy-2.4.8-installer.exe

**Comment by alincode** [comment]
已修正謝謝
