### ISSUE TITLE
「持續整合改善」頁面中的錯別字 

### ISSUE THREAD

**Issue by mjj2000** [readbook/learngeb#6]
```
## 結論
  
程式開發是一連串的協同合作，人為疏失是沒有辦法根絕的，但卻可以有機制讓問題及早發現，
TDD 正是一個良好的開發流程，讓開發過程包含了驗證機制，確保開發能量能夠被累積並且重覆使用，
隨著專案的成長，偵錯的能樣也會同步成長。
```

`能樣` => `能量` ?

https://github.com/readbook/learngeb/blob/master/TDD/continuous-improve.md

**Comment by alincode** [comment]
@mjj2000 

謝謝，已修正。

https://github.com/readbook/learngeb/commit/219d21da2ca976f112cb8c2fae3f2077190e1e78
